apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
  namespace: log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      containers:
      - name: log-generator
        image: alikingdom/loggeneator:0.7
        env:
        - name: DT_URL
          value: https://jmg62685.sprint.dynatracelabs.com
        - name: DT_LOG_INGEST_TOKEN
          value: dt0c01.5BBM2FUOQFQ4ZVPGYYOWS6XN.AGJ4M5XO7PEADGAJ44XI32TXTDLU5IGE5YR2OMDVOJF2GEBRZJTPYGZUITERBOGO